### ISSUE TITLE
Missing reference - Notifiable Canisters

### ISSUE THREAD

**Issue by SuddenlyHazel** [PsychedelicHQ/standards#1]
https://github.com/Psychedelic/standards/blob/8c9fe06c8f5a996242c9948275b69510a715c311/standards/token-interface/candid/token.did#L41

Can't seem to track down the type mentioned here.

**Comment by qti3e** [comment]
Hey! Sorry for the late response.
You're right and the type is not currently included but the method that is to be notified takes one arg that is a record with the given fields:

from: principal
to: principal
amount: nat64
